[project]
name = "llm"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "apyori>=1.1.2",
    "gensim>=4.4.0",
    "networkx>=3.6.1",
    "plotly>=6.7.0",
    "px>=0.2.2",
    "pyldavis>=3.4.1",
    "scikit-learn>=1.8.0",
    "selenium>=4.44.0",
    "torch>=2.12.0",
    "tqdm>=4.67.3",
    "webdriver-manager>=4.1.1",
    "wordcloud>=1.9.6",
    "yfinance>=1.4.1",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "jpype1>=1.7.1",
    "konlpy>=0.6.0",
    "pandas>=3.0.3",
]
